services:
  db:
    image: mysql:8.0
    container_name: zenbulle_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zenbulle
    ports:
      - "3307:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - zenbulle_data:/var/lib/mysql

volumes:
  zenbulle_data:
