export const ROUTES = {
  splash:         '/',
  selectionTheme: '/selection-theme',
  accueil:        '/accueil',
  connexion:      '/connexion',
  inscription:    '/inscription',
  questionnaire:  '/questionnaire',
  dashboard:      '/dashboard',
  journal:        '/journal',
  mesBulles:      '/mes-bulles',
  respiration:    '/respiration',
  emotion:        '/emotion',
  citations:      '/citations',
  menu:           '/menu',
};
